config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :places  do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: :destroy

  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  belongs_to :renter, class_name: "User", foreign_key: "user_id"
  belongs_to :place
  has_one :owner, through: :place

  # validates :start_date, presence: true
  # validates :end_date, presence: true

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  mount_uploader :photo, PhotoUploader

  validates :title, presence: true,  uniqueness: true
  validates :photo, presence: true

  # geocode stuff
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # validates :address, presence: true,  uniqueness: true
  # validates :description, presence: true
  # validates :price, presence: true
  # validates :destroy_pack, presence: true, inclusion: { in: ["Soil", "Damage", "Destroy"] }
  # validates :category, presence: true, inclusion: { in: ["House", "Field", "Hut", "Wharehouse", "Flat", "Castle", "Shop"] }
  # validates :rate, presence: true, inclusion: { in: [1,2,3,4,5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :bookings_as_renter, class_name: "Booking"
  has_many :bookings_as_owner, through: :places, source: :bookings


  mount_uploader :avatar, PhotoUploader
  # validates :name, presence: true, length: {minimum: 3}
  # validates :phone_number, presence: true
  # # validates :email, presence: true, uniqueness: true, format: { with: /\A.*@.*\.com\z/ }
  # validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def configure_permitted_parameters
     # For additional fields in app/views/devise/registrations/new.html.erb
     devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :email, :password, :avatar])

     # For additional in app/views/devise/registrations/edit.html.erb
     devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :email, :password, :avatar])
   end


  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all
  end

  def edit
  end

  def create
    @place = Place.find(params[:place_id])
    @booking = Booking.new(booking_params)
    @booking.owner = current_user
    @booking.place = @place
    @booking.renter = current_user
    authorize @place
    if @booking.save
      redirect_to dashboard_path
    else
      render "places/show"
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    @places = current_user.places
    # @places = Place.where(owner: current_user)
    @bookings = current_user.bookings_as_renter
    @email= current_user.email
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def home
    @places = Place.all
  end

  def index
    if params[:query].present?
      @query = params[:query]
      sql_query = "title ILIKE :query OR category ILIKE :query OR address ILIKE :query OR description ILIKE :query"
      @places = policy_scope(Place).order(created_at: :desc).where(sql_query, query: "%#{params[:query]}%")
    else
      @places = policy_scope(Place).order(created_at: :desc)
    end

    @marker_places = Place.where.not(latitude: nil, longitude: nil)

      @markers = @marker_places.map do |place|
        {
          lat: place.latitude,
          lng: place.longitude#,
          # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
        }
      end
    end


  def new
    @place = current_user.places.new
    authorize @place
  end

  def edit

  end

  def create
    @place = Place.new(place_params)
    @place.owner = current_user
    @place.tools = params[:place][:tools].join(" ").strip
    if @place.save!
      redirect_to places_path(@place)
    else
      render :new
    end
    authorize @place

  end

  def update
    authorize @place
    @place = current_user.places.update(place_params)
    redirect_to places_path
   end


  def show

    @booking = Booking.new
  end

  def destroy
    authorize @place
    @place.destroy
    redirect_to dashboard_path
  end

  private

  def place_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:place).permit(:title, :address, :description, :photo, :price, :equipment, :destroy_pack, :category, :rate, :sleepings, :tools)
  end

  def set_place
    @place = Place.find(params[:id])
    authorize @place
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Anger Party</title>
    <link rel="icon" type="image/png" sizes="32x32" href="http://res.cloudinary.com/dxjtno4gg/image/upload/v1527241596/frame_2.png">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/fullscreen-search' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>


  <!-- Stuff for GEOCODE -->
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>

  </body>
</html>

app/views/pages/dashboard.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <title>Profile page</title>
  </head>

  <body>

    <div class="profile-header-wrapper">
      <div class="profile-header-container text-center">

        <div class="profile-header-infos">
          <h1> Hello  <%= current_user.user_name %> ! </h1>
        </div>
        <div class="tabs">
          <button class="tablinks" onclick="openCity(event, 'booking-places')">My Bookings</button>
          <button class="tablinks" onclick="openCity(event, 'places-places')">My Places</button>
          <button class="tablinks" onclick="openCity(event, 'profile')">Profile</button>
        </div>
      </div>
    </div>


<!-- Tab content -->
  <div class="container">

    <div id="booking-places" class="tabcontent">
      <h3>My bookings </h3>
      <ul class="place_list">
        <% @bookings.each do |booking| %>
        <div class="row">
          <div class="col-xs-12 col-sm-4">
            <li class="place ">
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path booking.place.photo, height: 300, width: 400, crop: :fill %>');">

                <div class="card-category"><%= booking.place.owner.user_name %></div>
                <div class="card-description">
                  <h2><%= booking.place.title %></h2>
                  <p><span style="font-weight:bold"><%= booking.start_date %></span> to <span style="font-weight:bold"><%= booking.end_date %></span></p>
                </div>
                <%= cl_image_tag booking.place.owner.avatar, class: "card-user"%>

              </div>
              <%= link_to "Delete", booking_path(booking), method: :delete, data: { confirm: "Are you sure?" } %>
            </li>
            <br>
            <br>
          </div>
        </div>
        <% end %>
      </ul>
    </div>

    <div id="places-places" class="tabcontent">
      <h3>My places </h3>
      <ul class="place_list">
        <% @places.each do |place| %>
        <div class="row">
          <div class="col-xs-12 col-sm-4">
          <li class="place ">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path place.photo, height: 300, width: 400, crop: :fill %>');">

              <div class="card-category">Popular</div>
              <div class="card-description">
                <h2><%= place.title %></h2>
                <p><%= place.price %>€ - Pack <span style="font-weight:bold"><%= place.destroy_pack %></span></p>
              </div>
                          <%= cl_image_tag place.owner.avatar, class: "card-user"%>

              <a class="card-link" href="<%= place_path(place) %>" ></a>
            </div>
            <%= link_to "Delete", place_path(place),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
          </li>
          <br>
          <br>
          </div>
        </div>
        <% end %>
        </ul>
      </div>

    <div id="profile" class="tabcontent">
      <h3>My Profile</h3>
        <ul class="place_list">
            <p><%= current_user.user_name%></p>
            <p><%= current_user.email%></p>

            <p><%= link_to "/users/edit" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Edit Profile") %>
                <% end %></p>

            <p><%= link_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %></p>
            <p class="avatar"><%= cl_image_tag current_user.avatar %></p>
        </ul>
      </div>
  </div>

  </body>
</html>

app/views/pages/home.html.erb
<html>

<head>
  <meta charset="utf-8">
  <title>AngerParty at home</title>
</head>

<body>
  <%= render 'shared/banner' %>
  <div class="main-container">

    <div class="container">
      <h2 class="text-center">Popular Places</h2>
    </div>

    <div class="row">
      <% top_places = Place.last(3) %>
      <% top_places.each do |place| %>
        <div class="col-xs-12 col-sm-6 col-lg-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path place.photo, height: 300, width: 400, crop: :fill %>');">
            <div class="card-category">Villa</div>
            <div class="card-description">
              <h2><%= place.title %></h2>
              <p><%= place.price %>€ - Pack <span style="font-weight:bold"><%= place.destroy_pack %></span></p>
            </div>
            <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
            <a class="card-link" href="<%= place_path(place) %>" ></a>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</body>
</html>

app/views/places/_form.html.erb
<%= simple_form_for (@place)  do |t| %>

  <div class="form_section">
    <h3>General information</h2>
    <%= t.input :title %>
    <%= t.input :address, :input_html => { :placeholder => "ex: 5 rue du petit champs Paris" } %>
    <%= t.input :sleepings, :input_html => { :placeholder => "5" } %>
    <%= t.input :description, :input_html => { :placeholder => "Un lieu superbe, pour des soirées déjantées" }  %>
    <%= t.input :photo, label_html: { class: "btn-basic btn-purple btn-hover" }, input_html: { class: "hidden"} %>
    <%= t.input :photo_cache, as: :hidden %>
  </div>
  <div class="form_section">
  <h3>More about your place</h2>
    <%= t.input :equipment %>

   <div class="multiple-check">

         <fieldset class="form-group check_boxes optional place_tools">

           <label class="form-control-label integer optional">Destroying tools your propose</label>

           <div class="flex">
             <label for="place_tools_ball">
               <input name="place[tools][]" value="" type="hidden">
               <div class="form-check">
                 <input value="ball" name="place[tools][]" id="place_tools_ball" type="checkbox">
                 <div class="mass box">
                  <i class="fi fas fa-basketball-ball"></i></br>
                  <span for="place_tools_ball">Ball</span>
                   <p class="pack_descr">Throw basket ball everywhere and see what happen</p>
                 </div>
               </div>
             </label>

              <label for="place_tools_animal">
                <input name="place[tools][]" value="" type="hidden">
                <div class="form-check">
                  <input value="animal" name="place[tools][]" id="place_tools_animal" type="checkbox">
                  <div class="mass box">
                    <i class="fi fab fa-sticker-mule"></i></br>
                   <span for="place_tools_animal">Animal</span>
                    <p class="pack_descr">Mule, pig, cow... because animals can party to</p>
                  </div>
                </div>
              </label>

              <label for="place_tools_flame">
                <input name="place[tools][]" value="" type="hidden">
                <div class="form-check">
                  <input value="flame" name="place[tools][]" id="place_tools_flame" type="checkbox">
                  <div class="mass box">
                   <i class="fi fas fa-fire"></i></i></br>
                   <span for="place_tools_flame">Flame</span>
                    <p class="pack_descr">A bit risky but firefighters will join the party :D !</p>
                  </div>
                </div>
              </label>

           </div>

         </fieldset>

       </div>


  </div>

  <div class="form_section">

    <h3>Destroy options </h3>

    <p>Decide how far your guests can go while partying.</br> <span style="font-weight:bold;"> NB : AngerParty
      <span style="color:red;"> is not responsible</span> if it goes further than expected...</p></span>

    <div class="multiple-radio">

      <fieldset class="form-group radio_buttons optional place_destroy_pack">

        <div class="flex">

          <label for="place_destroy_pack_soil">
            <input name="place[destroy_pack]" value="" type="hidden">
            <div class="form-check">
              <input  value="soil" name="place[destroy_pack]" id="place_destroy_pack_soil" type="radio">
              <div class="soil box">
                <span for="place_destroy_pack_soil">Soil</span>
                <p class="pack_descr">You can soil, but with respect (vomit tolerated)</p>
              </div>
            </div>
          </label>

          <label for="place_destroy_pack_damage">
            <input name="place[destroy_pack]" value="" type="hidden">
            <div class="form-check">
              <input value="damage" name="place[destroy_pack]" id="place_destroy_pack_damage" type="radio">
              <div class="damage box">
                <span for="place_destroy_pack_damage">Damage</span>
                <p class="pack_descr">Get serious on breaking things</p>
              </div>
            </div>
          </label>

          <label for="place_destroy_pack_destroy">
            <input name="place[destroy_pack]" value="" type="hidden">
            <div class="form-check">
              <input value="destroy" name="place[destroy_pack]" id="place_destroy_pack_destroy" type="radio">
              <div class="destroy box">
                <span for="place_destroy_pack_destroy">Destroy</span>
                <p class="pack_descr">Unleash the dragon, the place has to return to hashes</p>
              </div>
            </div>
          </label>
        </div>

      </fieldset>

    </div>
    <%= t.input :price %>


  </div>

</br>

<%= t.submit html_options = {:class=>"btn-basic btn-green btn-hover"} %>

<% end %>

app/views/places/edit.html.erb
<h1>Edit this place</h1>
<%= render 'form', place: @place %>

app/views/places/index.html.erb
<div class="fluid-container">

   <div class="content">

    <div class="cards-container">

      <div class="list-intro">
        <div id="title">
          <h1>Our places to destroy</h1>
          <div id="your-search">
          <% if params[:query].present?%>
            <p>Your search : <span style="font-weight: bold">"<%=@query%>" </span></p>
            <%= link_to "Clean your search", places_path, html_options = {:class=>"btn-ghost"} %>
          <% end %>
          </div>
        </div>
        <% if policy(Place).create? %>
          <%= link_to "+ Add a new place", new_place_path, html_options = {:class=>"btn-basic btn-purple btn-hover", :id=>"add-btn"} %>
        <% end %>
      </div>

      <div class="row">

        <% @places.each do |place| %>

        <div class="col-xs-12 col-sm-6 col-lg-4">

          <div class="card" style="background-image: url('<%= cl_image_path place.photo, height: 300, width: 400, crop: :fill %>')">
            <div class="card-category">Villa</div>
            <div class="card-description">
              <h2><%= place.title %></h2>
              <p><%= place.price %>€ - Pack <span style="font-weight:bold"><%= place.destroy_pack %></span></p>
            </div>
            <%= cl_image_tag place.owner.avatar, class: "card-user"%>


            <a class="card-link" href="<%= place_path(place) %>" ></a>
          </div>

        </div>

      <% end %>

      </div>

    </div>

    <div id="map" data-markers="<%= @markers.to_json %>">
    </div>

  </div>

</div>

app/views/places/new.html.erb
<div class="main-container">

<h1>Create a new place</h1>


  <div class="form">
    <%= render 'form', place: @place %>
  </div>

</div>

<% if policy(Place).create? %>
  <%= render 'form', place: @place %>
<% end %>

app/views/places/show.html.erb
<div class="container">

  <div class="place_banner">
    </br>
    </br>
    <%= link_to "Back to the list", places_path, class: "btn-basic btn-purple btn-hover"  %>
    </br>
    </br>
    <h1><span style="font-size: 20px; color: #262626">Villa</span></br>

    <%= @place.title %></h1>

    <div class="place_hero" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @place.photo, height: 300, width: 400, crop: :fill %>');">
    </div>
  </div>


<div class="show-content">

  <div class="details">

      <ul class="grid-container">
        <li class="grid-item"><p><span style="font-weight: bold"> Address: </span> <%= @place.address %></p></li>
        <li class="grid-item"><p><span style="font-weight: bold"> Description: </span><%= @place.description %></p></li>
        <li class="grid-item"><p><span style="font-weight: bold"> Price: </span><%= @place.price %>€ /Hour</p></li>
        <li class="grid-item"><p><span style="font-weight: bold"> Equipment: </span><%= @place.equipment %></p></li>
        <li class="grid-item"><p><span style="font-weight: bold"> Destroy pack: </span><%= @place.destroy_pack %></p></li>
        <li class="grid-item"><p><span style="font-weight: bold"> Sleepings: </span><%= @place.sleepings %></p></li>
        <li class="grid-item"><p><span style="font-weight: bold"> Tools: </span><%= @place.tools %></p></li>
        <li class="grid-item"><p><span style="font-weight: bold"> Owner: </span><%= @place.owner.user_name %></p></li>
      </ul>

      <%= link_to "Edit this place", edit_place_path(@place.id), :class => "btn-basic btn-purple btn-hover"%></br></br>


  </div>


  <%# form BOOKING  %>
  <div id="booking-form">
    <h2 class="text-center"> Book this place</h2>
    <%= simple_form_for [@place, @booking] do |f| %>

      <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {id: "range_end"}  %>

      <%= f.submit "Confirm booking", class: "btn-basic btn-green btn-hover" %>
    <% end %>

  </div>

</div>

<% unless @place.address.blank? %>
  <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x300&sensor=false&maptype=roadmap&markers=color:purple|#{@place.address}", id:"show_map" %>
<% end %>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: url('https://i.imgur.com/BUg1F8L.jpg');">
      <div class="banner-content">
        <h1>DESTROY EVERYTHING AT HOME</h1>
        <p>Find unique places to party, go wild and destroy everything</p>

    <%= render 'shared/search-form' %>

  </div>
</div>

app/views/shared/_card.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <!-- insert <div class="card"> -->
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Le Wagon Shanghai</h2>
          <p>Very cool city, the best</p>
        </div>
        <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
        <a class="card-link" href="#" ></a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made by Anger Party
  </div>
</div>

app/views/shared/_fullscreen-search.html.erb
 <div id="myOverlay" class="overlay">
  <span class="closebtn" onclick="closeSearch()" title="Close Overlay"><i class="fas fa-close"></i></span>
  <div class="overlay-content">
      <%= form_tag places_path, method: :get, :class => 'form-inline' do %>
          <p>Type something and hit enter</p>
          <%= text_field_tag :query,
            params[:query],
            placeholder: "Type here..(ex: Lyon, manor, big house)"
          %>
      <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <div id="navbar-left">

    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png", height: 50 %>
    <% end %>
    <% if user_signed_in? %>

    <% end %>

  </div>

  <!-- Right Navigation -->
  <div>

    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <% if user_signed_in? %>

        <!-- Links when logged in -->
        <button type="submit" onclick="openSearch()" style="color: #FF003D" class="navbar-wagon-link">
          <i class="fas fa-search"></i> Search
        </button>
        <%= link_to "Places", "/places", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Submit new place", "/places/new", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Dashboard", "/dashboard", class: "navbar-wagon-item navbar-wagon-link" %>

        <!--
        <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Help", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      -->

        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "/users/edit" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>

        <!-- Login link (when logged out) -->
      <%= link_to "Discover all our Places", "/places", class: "navbar-wagon-item navbar-wagon-link" %>
      <div class="btn btn-default">
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      </div>
    </div>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search-form.html.erb
<div id="search-bar">
  <%= form_tag places_path, method: :get, :class => 'form-inline' do %>
    <div class="form-group">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Ex : Paris, manor, big house ..."
    %>
    </div>
    <button type="submit" class="btn-basic btn-icon btn-pink btn-hover">
      <i class="fas fa-search"></i>
    </button>
  <% end %>
</div>